/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/qyIc7p0Pi2G
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { User } from "@/types/user.types";

type ChatProps = {
  sender: User;
  receiver: User;
}

function getInitials(name: string) {
  const [firstName, lastName] = name.split(' ');
  return `${firstName?.charAt(0)}${lastName?lastName.charAt(0): ''}`;
}

export function Chat( { sender, receiver }: ChatProps ) {
  return (
    <div className="container grid h-[90vh] w-full overflow-hidden">
      <div className="flex h-full flex-col">
        <div className="flex h-14 items-center justify-between border-b px-4 dark:border-gray-800">
          <div className="flex items-center gap-2">
            <Avatar>
              <AvatarImage src={receiver.image} />
              <AvatarFallback>{getInitials(receiver.username)}</AvatarFallback>
            </Avatar>
            <div>
              <h4 className="font-medium">{receiver.username}</h4>
              <p className="text-sm text-gray-500 dark:text-gray-400">Online</p>
            </div>
          </div>
        </div>
        <div className="flex-1 overflow-auto p-4">
          <div className="grid gap-4">
            <div className="flex items-end gap-2">
              <Avatar>
                <AvatarImage src="/placeholder-user.jpg" />
                <AvatarFallback>JD</AvatarFallback>
              </Avatar>
              <div className="max-w-[70%] rounded-lg bg-gray-100 p-3 text-sm dark:bg-gray-800">
                <p>Hello, how are you?</p>
                <span className="mt-1 block text-xs text-gray-500 dark:text-gray-400">12:34 PM</span>
              </div>
            </div>
            <div className="flex justify-end items-end gap-2">
              <div className="max-w-[70%] rounded-lg bg-primary p-3 text-sm text-white">
                <p>I&apos;m doing great, thanks for asking!</p>
                <span className="mt-1 block text-xs opacity-80">12:35 PM</span>
              </div>
              <Avatar>
                <AvatarImage src="/placeholder-user.jpg" />
                <AvatarFallback>JD</AvatarFallback>
              </Avatar>
            </div>
            <div className="flex items-end gap-2">
              <Avatar>
                <AvatarImage src="/placeholder-user.jpg" />
                <AvatarFallback>JD</AvatarFallback>
              </Avatar>
              <div className="max-w-[70%] rounded-lg bg-gray-100 p-3 text-sm dark:bg-gray-800">
                <p>Did you see the new design I sent you?</p>
                <span className="mt-1 block text-xs text-gray-500 dark:text-gray-400">12:36 PM</span>
              </div>
            </div>
            <div className="flex justify-end items-end gap-2">
              <div className="max-w-[70%] rounded-lg bg-primary p-3 text-sm text-white">
                <p>Yes, I did! It looks great, nice work.</p>
                <span className="mt-1 block text-xs opacity-80">12:37 PM</span>
              </div>
              <Avatar>
                <AvatarImage src="/placeholder-user.jpg" />
                <AvatarFallback>JD</AvatarFallback>
              </Avatar>
            </div>
          </div>
        </div>
        <div className="border-t px-4 py-3 dark:border-gray-800">
          <div className="flex items-center gap-2">
            <Input type="text" placeholder="Type your message..." className="flex-1" />
            <Button>Send</Button>
          </div>
        </div>
      </div>
    </div>
  )
}

type ChatMessageProps = {
  message: string;
  sender: User;
  timestamp: string;
}

function ChatMessage(props: ChatMessageProps) {
  return (
    <div className="flex items-end gap-2">
      <Avatar>
        <AvatarImage src={props.sender.image} />
        <AvatarFallback>{getInitials(props.sender.username)}</AvatarFallback>
      </Avatar>
      <div className="max-w-[70%] rounded-lg bg-gray-100 p-3 text-sm dark:bg-gray-800">
        <p>{props.message}</p>
        <span className="mt-1 block text-xs text-gray-500 dark:text-gray-400">{props.timestamp}</span>
      </div>
    </div>
  )
}
